# Generated by Django 4.2.4 on 2023-09-06 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_change_user_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Change_User_Model',
            new_name='Extra_Information',
        ),
    ]
