# Generated by Django 4.2.4 on 2023-09-06 15:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_change_user_model_extra_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra_Information',
            new_name='Profile',
        ),
    ]
