# Generated by Django 4.2.4 on 2023-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
